---
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${device_comment}

packages:
  wifi: !include wifi.yaml
  ota: !include ota.yaml
  api: !include api.yaml
  logging: !include logging.yaml
  sensors: !include sensors.yaml
  webserver: !include webserver.yaml
