---
sensor:
  - platform: uptime
    name: ${friendly_name} Uptime
    update_interval: 300s
    entity_category: "diagnostic"

text_sensor:
  - platform: version
    name: ${friendly_name} Version

binary_sensor:
  - platform: status
    # Status for helping see if it is online
    name: "${name} Status"