substitutions:
  name: "basement-wall-outlet"
  friendly_name: "Basement Wall Outlet"
  api_encryption_key: !secret basement_wall_outlet_encryption_key

packages:
  base: !include ./common/base.yaml
  device: !include ./devices/elegrp-rrr00.yaml
